version: 2

project-config:
  caching:
  - &cache_dependencies ${CACHE_VERSION}-dependencies
  - cache_default_paths: &cache_default_paths
    - ~/.m2
  docker:
  # Latest 181 version has a bug with surefire
  - docker_build: &docker_build
    - image: circleci/openjdk:8u171-jdk

jobs:
  verify-deploy:
    docker: *docker_build
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Start the KAAS deployment
        command: make start
    - restore_cache:
        keys:
        - *cache_dependencies
    - run:
        name: Provision the KAAS database
        command: make db-build
    - run:
        name: Test the KAAS proxy is working
        command: >
          docker-compose -f docker/docker-compose.yml exec kaas-proxy
          sh -c "wget -O- localhost:80/api/team 2>/dev/null" | grep SKUM
    - run:
        name: Stop the KAAS deployment
        when: always
        command: make kill
    - save_cache:
        paths: *cache_default_paths
        key: *cache_dependencies

workflows:
  version: 2
  verify-deploy:
    jobs:
    - verify-deploy:
        filters:
          branches:
            only: master
